import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('Upgrade preserves legacy data; plan isolation, owners, archives and same-email membership',async()=>{
 const db=new PGlite();const a='11111111-1111-4111-8111-111111111111',b='22222222-2222-4222-8222-222222222222';
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);grant usage on schema public to service_role;`);
 await db.exec(await readFile(new URL('../supabase/01_schema.sql',import.meta.url),'utf8'));
 await db.query('insert into auth.users values($1,$2,now()),($3,$4,now())',[a,'office@hound-capital.com',b,'other@example.com']);
 await db.exec(await readFile(new URL('../supabase/02_grant_admin.sql',import.meta.url),'utf8'));
 const rpc=async(method,body={},email=null,user=a)=>(await db.query('select public.dateeye_state($1,$2::jsonb,$3,$4::uuid) result',[method,JSON.stringify(body),email,user])).rows[0].result;
 const event={name:'Original',startDate:'2026-10-01',endDate:'2026-10-31',members:['A','B','C']};
 await db.exec('set role service_role');await rpc('POST',event);const old=await rpc('GET');const first=old.members[0];
 await rpc('PATCH',{action:'member',id:first.id,name:'A',email:'same@example.com',active:true});
 await rpc('PUT',{memberId:first.id,date:'2026-10-10',available:true},'same@example.com');
 await db.exec('reset role');const migration=await readFile(new URL('../supabase/03_multi_plan.sql',import.meta.url),'utf8');await db.exec(migration);await db.exec(migration);
 await db.query('insert into public.dateeye_admins values($1,$2)',[b,'other@example.com']);
 await db.exec('set role service_role');
 const legacy=await rpc('GET',{},'same@example.com');assert.equal(legacy.event.id,old.event.id);assert.equal(legacy.availability.length,1);
 const second=await rpc('POST',{...event,name:'Second',planId:'new'});assert.ok(second.planId);assert.notEqual(second.planId,old.event.id);
 const s=await rpc('GET',{planId:second.planId});assert.equal(s.members.length,3);assert.equal(s.availability.length,0);
 await rpc('PATCH',{planId:second.planId,action:'member',id:s.members[0].id,name:'A',email:'same@example.com',active:true});
 const guest=await rpc('GET',{planId:second.planId},'same@example.com');assert.equal(guest.viewer.memberId,s.members[0].id);assert.equal(guest.members.length,3);assert.equal(guest.availability.length,0);
 await assert.rejects(()=>rpc('PUT',{planId:second.planId,memberId:first.id,date:'2026-10-10',available:false},'same@example.com'));
 await rpc('PUT',{planId:second.planId,memberId:s.members[0].id,date:'2026-10-10',available:false},'same@example.com');
 assert.equal((await rpc('GET',{},'same@example.com')).availability[0].available,true);
 assert.equal((await rpc('GET',{planId:second.planId},'same@example.com')).availability[0].available,false);
 assert.equal((await rpc('GET',{view:'plans'})).plans.length,2);
 assert.equal((await rpc('GET',{view:'plans'},null,b)).plans.length,0);
 await assert.rejects(()=>rpc('GET',{planId:second.planId},null,b));
 await assert.rejects(()=>rpc('PATCH',{planId:second.planId,action:'archive',archived:true},null,b));
 await assert.rejects(()=>rpc('GET',{view:'plans',planId:second.planId},'same@example.com'));
 await rpc('PATCH',{planId:second.planId,action:'archive',archived:true});
 await assert.rejects(()=>rpc('GET',{planId:second.planId},'same@example.com'));
 await assert.rejects(()=>rpc('PUT',{planId:second.planId,memberId:s.members[0].id,date:'2026-10-10',available:true},'same@example.com'));
 assert.equal((await rpc('GET',{planId:second.planId})).event.archived,true);
 await rpc('PATCH',{planId:second.planId,action:'archive',archived:false});
 assert.equal((await rpc('GET',{planId:second.planId},'same@example.com')).availability[0].available,false);
 await db.exec('reset role');await db.exec('set role anon');await assert.rejects(()=>rpc('GET',{view:'plans'}));
 }finally{await db.close();}
});
