import test from 'node:test';
import assert from 'node:assert/strict';
import {createClient,ApiError} from '../src/session-client.ts';
function fixture(initial,transport){let value=initial;const store={read:async()=>value,write:async s=>{value=s;},clear:async()=>{value=null;}};return {client:createClient('https://prod-plan.com',store,transport),value:()=>value};}
const fresh={accessToken:'current',refreshToken:'refresh',expiresAt:Date.now()+3600000};
test('only HTTPS origins can receive session tokens',()=>{assert.throws(()=>createClient('http://prod-plan.com',{}));assert.throws(()=>createClient('https://user:password@prod-plan.com',{}));assert.throws(()=>createClient('https://prod-plan.com/other',{}));});
test('verified session is persisted and authenticated reads send its bearer token',async()=>{const f=fixture(null,async(url,init)=>{if(url.endsWith('/session'))return Response.json({accessToken:'jwt',refreshToken:'refresh',expiresIn:3600});assert.equal(init.headers.Authorization,'Bearer jwt');return Response.json({plans:[]});});await f.client.verifyCode('you@example.com','123456');assert.equal(f.value().accessToken,'jwt');assert.deepEqual(await f.client.request('/api/state?view=plans'),{plans:[]});});
test('concurrent requests refresh a near-expired session only once',async()=>{let refreshes=0;const f=fixture({...fresh,expiresAt:0},async(url,init)=>{if(url.endsWith('/refresh')){refreshes++;await Promise.resolve();return Response.json({accessToken:'new',refreshToken:'rotated',expiresIn:3600});}assert.equal(init.headers.Authorization,'Bearer new');return Response.json({ok:true});});await Promise.all([f.client.request('/api/profile'),f.client.request('/api/profile')]);assert.equal(refreshes,1);assert.equal(f.value().refreshToken,'rotated');});
test('expired refresh clears local session',async()=>{const f=fixture({...fresh,expiresAt:0},async()=>Response.json({error:'Expired'},{status:401}));await assert.rejects(f.client.request('/api/profile'),ApiError);assert.equal(f.value(),null);});
test('network errors preserve the session for retry',async()=>{const f=fixture({...fresh,expiresAt:0},async()=>{throw Error('Offline');});await assert.rejects(f.client.request('/api/profile'),/Offline/);assert.ok(f.value());});
test('a 401 refreshes and retries once; a persistent 401 clears the session',async()=>{let calls=0;const f=fixture(fresh,async url=>{if(url.endsWith('/refresh'))return Response.json({accessToken:'new',refreshToken:'rotated',expiresIn:3600});calls++;return Response.json({error:'Expired'},{status:401});});await assert.rejects(f.client.request('/api/profile'),ApiError);assert.equal(calls,2);assert.equal(f.value(),null);});
test('401 retry preserves the mutation payload; 403 does not refresh',async()=>{let attempts=0;const f=fixture(fresh,async(url,init)=>{if(url.endsWith('/refresh'))return Response.json({accessToken:'new',refreshToken:'r',expiresIn:3600});assert.equal(init.method,'PUT');assert.deepEqual(JSON.parse(init.body),{available:true});return ++attempts===1?Response.json({error:'Expired'},{status:401}):Response.json({ok:true});});await f.client.request('/api/state','PUT',{available:true});assert.equal(attempts,2);const denied=fixture(fresh,async url=>{assert.ok(!url.endsWith('/refresh'));return Response.json({error:'Denied'},{status:403});});await assert.rejects(denied.client.request('/api/profile'),e=>e.status===403);assert.ok(denied.value());});
