import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, BackHandler, Image, KeyboardAvoidingView, Linking, Platform, Pressable, ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import * as WebBrowser from 'expo-web-browser';
import { api } from './src/api';
import { ApiError } from './src/session-client';
import { dateKey, invitation, localDate, monthCells, rankedDates, TERMS_VERSION, validatePlan, WEBSITE, type Member, type Plan, type PlanState, type Profile } from './src/domain';

const coral='#E97868', teal='#397E7B', ink='#263D40', muted='#6E7D7D';
const demoPlan: PlanState={event:{id:'demo',name:'A weekend together',startDate:'2026-10-10',endDate:'2026-10-25'},members:[{id:'oliver',name:'Oliver',active:1},{id:'poppy',name:'Poppy',active:1},{id:'henry',name:'Henry',active:1}],availability:[{memberId:'oliver',date:'2026-10-17',available:true},{memberId:'poppy',date:'2026-10-17',available:true},{memberId:'henry',date:'2026-10-17',available:true}],viewer:{isAdmin:true,memberId:'oliver',email:'demo@example.com'}};
type Screen='plans'|'create'|'plan'|'account';
function Button({label,onPress,disabled=false,secondary=false}:{label:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}) {return <Pressable accessibilityRole="button" accessibilityState={{disabled}} onPress={onPress} disabled={disabled} style={[s.button,secondary&&s.secondary,disabled&&s.disabled]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{label}</Text></Pressable>;}
function Field({label,value,onChange,placeholder,keyboardType='default',maxLength=120}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;keyboardType?:'default'|'email-address'|'number-pad';maxLength?:number}) {return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} style={s.input} value={value} onChangeText={onChange} placeholder={placeholder} keyboardType={keyboardType} autoCapitalize={keyboardType==='default'?'sentences':'none'} autoCorrect={false} maxLength={maxLength}/></View>;}
function Choices({label,values,value,onChange}:{label:string;values:string[];value:string;onChange:(v:string)=>void}) {return <View style={s.field}><Text style={s.label}>{label}</Text><View style={s.choices}>{values.map(v=><Pressable key={v} accessibilityRole="radio" accessibilityState={{checked:v===value}} onPress={()=>onChange(v)} style={[s.chip,v===value&&s.chipSelected]}><Text style={v===value?s.selectedText:s.body}>{v}</Text></Pressable>)}</View></View>;}
async function openPage(path: string) {await WebBrowser.openBrowserAsync(WEBSITE+path);}
function LegalLinks() {return <View style={s.legal}><Button label="terms." secondary onPress={()=>{void openPage('/terms').catch(()=>Alert.alert('Could not open terms','Please visit '+WEBSITE+'/terms.'));}}/><Button label="Help!" secondary onPress={()=>{void Linking.openURL('mailto:office@hound-capital.com').catch(()=>Alert.alert('Contact us','office@hound-capital.com'));}}/></View>;}

export default function App() {return <SafeAreaProvider><Main/></SafeAreaProvider>;}
function Main() {
  const [signedIn,setSignedIn]=useState(false), [demo,setDemo]=useState(false),[booting,setBooting]=useState(true);
  const [startInSettings,setStartInSettings]=useState(false);
  const [screen,setScreen]=useState<Screen>('plans'),[selected,setSelected]=useState<PlanState|null>(null),[plans,setPlans]=useState<Plan[]>([]),[profile,setProfile]=useState<Profile|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[archived,setArchived]=useState(false);
  async function run(action:()=>Promise<void>) {setBusy(true);setError('');try {await action();}catch(e){setError(e instanceof Error?e.message:'Please try again.');if(e instanceof ApiError && e.status===401){setSignedIn(false);setProfile(null);setSelected(null);setPlans([]);setScreen('plans');}}finally{setBusy(false);}}
  async function loadPlans() {const data=await api.request<{plans:Plan[]}>('/api/state?view=plans');setPlans(data.plans);}
  async function enter() {const data=await api.request<Profile>('/api/profile');setProfile(data);setSignedIn(true);if(data.profile&&data.termsVersion===TERMS_VERSION)await loadPlans();}
  useEffect(()=>{let alive=true;void api.readSession().then(async session=>{if(session&&alive)await run(enter);}).catch(()=>{if(alive)setError('Could not restore your session. Please sign in.');}).finally(()=>{if(alive)setBooting(false);});return()=>{alive=false;};},[]);
  useEffect(()=>{const sub=BackHandler.addEventListener('hardwareBackPress',()=>{if(screen!=='plans'){setScreen('plans');return true;}return false;});return()=>sub.remove();},[screen]);
  function startDemo(){setDemo(true);setSelected(structuredClone(demoPlan));setPlans([demoPlan.event]);setScreen('plans');setError('');}
  async function openPlan(id:string){setStartInSettings(false);if(demo){setScreen('plan');return;}await run(async()=>{const state=await api.request<PlanState>('/api/state?plan='+encodeURIComponent(id));setSelected(state);setScreen('plan');});}
  async function savePlan(payload:unknown,method='PATCH'){if(!selected)return;const id=selected.event.id;if(demo)return;await api.request('/api/state?plan='+encodeURIComponent(id),method,payload);setSelected(await api.request<PlanState>('/api/state?plan='+encodeURIComponent(id)));}
  async function signOut(){await run(async()=>{if(!demo)await api.request('/api/logout','POST',{});await api.clearSession();setDemo(false);setSignedIn(false);setProfile(null);setSelected(null);setPlans([]);setScreen('plans');});}
  return <SafeAreaView style={s.safe}><StatusBar style="dark"/><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==='ios'?'padding':undefined}>
    <View style={s.header}><Image source={require('./assets/prod-logo.png')} style={s.logo} accessibilityLabel="prod." resizeMode="contain"/>{(signedIn||demo)&&<Button label={screen==='plans'?'Account':'My plans'} secondary disabled={busy} onPress={()=>{setError('');setScreen(screen==='plans'?'account':'plans');}}/>}</View>
    <ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
      {demo&&<View style={s.notice}><Text style={s.noticeText}>Demo · sample plans only. Nothing is sent or saved.</Text><Button label="Exit demo" secondary onPress={()=>{setDemo(false);setSelected(null);setPlans([]);setScreen('plans');}}/></View>}
      {error!==''&&<Text accessibilityRole="alert" style={s.error}>{error}</Text>}
      {booting?<ActivityIndicator color={teal}/>:!signedIn&&!demo?<SignIn busy={busy} onDemo={startDemo} run={run} onVerified={enter}/>:
      !demo&&(!profile?.profile||profile.termsVersion!==TERMS_VERSION)?<Registration profile={profile} busy={busy} run={run} onReady={enter}/>:
      screen==='account'?<Account demo={demo} email={profile?.email||'demo@example.com'} busy={busy} signOut={()=>{void signOut();}} run={run} onDeleted={()=>{setSignedIn(false);setProfile(null);setSelected(null);setPlans([]);setScreen('plans');}}/>:
      screen==='create'?<NewPlan busy={busy} demo={demo} run={run} onCreate={async values=>{const data=await api.request<{planId:string}>('/api/state?plan=new','POST',values);const state=await api.request<PlanState>('/api/state?plan='+data.planId);setSelected(state);setStartInSettings(true);await loadPlans();setScreen('plan');}}/>:
      screen==='plan'&&selected?<PlanPage state={selected} initialSettings={startInSettings} demo={demo} busy={busy} run={run} save={savePlan} onToggle={async date=>{const memberId=selected.viewer.memberId;if(!memberId)return;const available=!selected.availability.find(a=>a.memberId===memberId&&a.date===date)?.available;if(demo){setSelected({...selected,availability:[...selected.availability.filter(a=>!(a.memberId===memberId&&a.date===date)),{memberId,date,available}]});return;}await savePlan({memberId,date,available},'PUT');}}/>:
      <><Text style={s.eyebrow}>LESS BACK AND FORTH.</Text><Text style={s.title}>My plans</Text><Text style={s.subtitle}>More getting together.</Text><Button label="Make a plan" disabled={busy||demo} onPress={()=>setScreen('create')}/><View style={s.choices}><Button label="Active" secondary disabled={busy} onPress={()=>setArchived(false)}/><Button label="Archived" secondary disabled={busy} onPress={()=>setArchived(true)}/>{!demo&&<Button label="Refresh" secondary disabled={busy} onPress={()=>{void run(loadPlans);}}/>}</View>
      {plans.filter(p=>!!p.archived===archived).map(p=><View key={p.id} style={s.card}><Text style={s.heading}>{p.name}</Text><Text style={s.body}>{p.startDate} — {p.endDate}</Text><Button label="Open plan" disabled={busy} onPress={()=>{void openPlan(p.id);}}/>{!demo&&<Button label={p.archived?'Restore':'Archive'} secondary disabled={busy} onPress={()=>{void run(async()=>{await api.request('/api/state?plan='+p.id,'PATCH',{action:'archive',archived:!p.archived});await loadPlans();});}}/>}</View>)}
      {!plans.some(p=>!!p.archived===archived)&&<Text style={s.body}>{archived?'No archived plans.':'No active plans yet. Make your first plan.'}</Text>}</>}
      {busy&&<ActivityIndicator style={s.loading} color={teal}/>}
      <LegalLinks/><Text style={s.copyright}>© Hound Capital Ltd 2026</Text>
    </ScrollView>
  </KeyboardAvoidingView></SafeAreaView>;
}
function SignIn({busy,run,onVerified,onDemo}:{busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;onVerified:()=>Promise<void>;onDemo:()=>void}) {
  const [email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false);
  return <><Text style={s.eyebrow}>GOOD PLANS START WITH A LITTLE PROD.</Text><Text style={s.title}>Bring your people together.</Text><Text style={s.subtitle}>Sign in to find a date that works.</Text><View style={s.card}>
  {!sent?<><Field label="Your email" value={email} onChange={setEmail} placeholder="you@example.com" keyboardType="email-address" maxLength={254}/><Button label="Send sign-in code" disabled={busy} onPress={()=>{void run(async()=>{if(!/^\S+@[^\s@]+\.[^\s@]+$/.test(email.trim()))throw Error('Enter a valid email address.');await api.sendCode(email.trim().toLowerCase());setSent(true);});}}/></>:<><Text style={s.body}>Check {email}. Enter your sign-in code below. If your email contains a confirmation link, open it first, then return here to enter the code sent afterwards.</Text><Field label="Sign-in code" value={code} onChange={setCode} keyboardType="number-pad" maxLength={10}/><Button label="Verify email" disabled={busy} onPress={()=>{void run(async()=>{if(!/^\d{6,10}$/.test(code))throw Error('Enter the code from your email.');await api.verifyCode(email.trim().toLowerCase(),code);await onVerified();});}}/><Button label="Change email or resend" secondary disabled={busy} onPress={()=>{setSent(false);setCode('');}}/></>}
  </View><Text style={s.body}>New to prod.? Register on the website, then sign in here. prod. is for people aged 18 or over.</Text><Button label="Register" secondary onPress={()=>{void openPage('/register').catch(()=>Alert.alert('Register',WEBSITE+'/register'));}}/><Button label="Explore a sample plan" secondary onPress={onDemo}/></>;
}
function Registration({profile,busy,run,onReady}:{profile:Profile|null;busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;onReady:()=>Promise<void>}) {
  const [name,setName]=useState(''),[sex,setSex]=useState('Prefer not to say'),[age,setAge]=useState(''),[agree,setAgree]=useState(false);
  return <><Text style={s.title}>{profile?.profile?'Updated terms':'Your details'}</Text><Text style={s.body}>Complete your adult registration before creating plans.</Text>{!profile?.profile&&<><Field label="Name" value={name} onChange={setName} maxLength={80}/><Choices label="Sex" value={sex} onChange={setSex} values={['Female','Male','Intersex','Prefer not to say']}/><Choices label="Age" value={age} onChange={setAge} values={['Under 18','18–24','25–34','35–44','45–54','55–64','65+']}/></>}
  <Pressable accessibilityRole="checkbox" accessibilityState={{checked:agree}} style={s.checkbox} onPress={()=>setAgree(!agree)}><Text style={s.body}>{agree?'☑':'☐'} I agree to the Terms of Service and acknowledge the Privacy Policy.</Text></Pressable>
  <Button label="Agree and continue" disabled={busy||!agree} onPress={()=>{void run(async()=>{if(profile?.profile)await api.request('/api/accept-terms','POST',{termsAccepted:true,termsVersion:TERMS_VERSION});else {if(!age||age==='Under 18')throw Error('prod. is only for people aged 18 or over.');if(!name.trim())throw Error('Enter your name.');await api.request('/api/profile','POST',{name:name.trim(),sex,ageRange:age,termsAccepted:true,termsVersion:TERMS_VERSION});}await onReady();});}}/></>;
}
function NewPlan({busy,demo,run,onCreate}:{busy:boolean;demo:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;onCreate:(value:unknown)=>Promise<void>}) {
  const [name,setName]=useState(''),[from,setFrom]=useState(dateKey(new Date())),[to,setTo]=useState(dateKey(new Date())),[names,setNames]=useState('');
  return <><Text style={s.title}>What’s the plan?</Text><Text style={s.subtitle}>Add your dates and people. Then finish their details in Event settings.</Text><Field label="Event name" value={name} onChange={setName} placeholder="A weekend away"/><Field label="From (YYYY-MM-DD)" value={from} onChange={setFrom} maxLength={10}/><Field label="To (YYYY-MM-DD)" value={to} onChange={setTo} maxLength={10}/><Field label="Who’s coming?" value={names} onChange={setNames} placeholder="Oliver, Henry, Eric, Poppy" maxLength={4000}/><Text style={s.body}>Separate names with commas. Include yourself if you’re coming.</Text><Button label="Continue to event settings" disabled={busy||demo} onPress={()=>{void run(async()=>{const members=names.split(',').map(n=>n.trim()).filter(Boolean);validatePlan(name,from,to,members);await onCreate({name:name.trim(),startDate:from,endDate:to,members});});}}/></>;
}
function PlanPage({state,initialSettings,demo,busy,run,save,onToggle}:{state:PlanState;initialSettings:boolean;demo:boolean;busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;save:(payload:unknown,method?:string)=>Promise<void>;onToggle:(date:string)=>Promise<void>}) {
  const [tab,setTab]=useState<'calendar'|'results'|'settings'>(initialSettings?'settings':'calendar'),[month,setMonth]=useState(()=>localDate(state.event.startDate));
  useEffect(()=>{setMonth(localDate(state.event.startDate));setTab(initialSettings?'settings':'calendar');},[state.event.id,initialSettings]);
  const matches=rankedDates(state),ownId=state.viewer.memberId;
  const previous=new Date(month.getFullYear(),month.getMonth()-1,1),next=new Date(month.getFullYear(),month.getMonth()+1,1);
  return <><Text style={s.title}>{state.event.name}</Text><Text style={s.body}>{state.event.startDate} — {state.event.endDate} · {state.members.length} people</Text>{state.event.archived&&<Text style={s.noticeText}>Archived · responses are read-only.</Text>}
  <View style={s.choices}><Button label="Calendar" secondary onPress={()=>setTab('calendar')}/><Button label="Best dates" secondary onPress={()=>setTab('results')}/>{!demo&&<Button label="Event settings" secondary onPress={()=>setTab('settings')}/>}</View>
  {tab==='settings'?<><Text style={s.heading}>Event settings</Text><Text style={s.body}>Add each person’s email. Match your own email to your member entry to mark your availability. Invitations use the current website response flow; verified invitee sign-in is a later mobile milestone.</Text>{state.managedMembers?.map(m=><MemberEditor key={m.id+':'+m.email+':'+m.active} member={m} busy={busy} run={run} save={save}/>)}<MemberEditor busy={busy} run={run} save={save}/></>:
  tab==='results'?<><Text style={s.heading}>Dates that work</Text><Text style={s.body}>Dates where more than half of your group are available.</Text>{matches.map(row=><View key={row.date} style={s.card}><Text style={s.heading}>{localDate(row.date).toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long'})}</Text><Text style={s.body}>{row.count} of {state.members.length} available · {row.names.join(', ')}</Text><Text style={s.noticeText}>{row.count===state.members.length?'Everyone is free':'Most people are free'}</Text></View>)}{!matches.length&&<Text style={s.body}>No majority dates yet. More responses will help.</Text>}</>:
  <><Text style={s.heading}>When are you free?</Text><Text style={s.body}>Tap once for available. Tap again for unavailable. Empty dates have no response.</Text>{!ownId&&!state.event.archived&&<Text style={s.noticeText}>Add your sign-in email to your member entry in Event settings to respond.</Text>}
  <View style={s.month}><Button label="‹" secondary disabled={dateKey(new Date(previous.getFullYear(),previous.getMonth()+1,0))<state.event.startDate} onPress={()=>setMonth(previous)}/><Text style={s.heading}>{month.toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</Text><Button label="›" secondary disabled={dateKey(next)>state.event.endDate} onPress={()=>setMonth(next)}/></View>
  <View style={s.grid}>{['M','T','W','T','F','S','S'].map((d,i)=><View key={'heading'+i} style={s.day}><Text style={s.dayLabel}>{d}</Text></View>)}{monthCells(month).map((date,i)=>{if(!date)return <View key={'blank'+i} style={s.day}/>;const outside=date<state.event.startDate||date>state.event.endDate;const own=state.availability.find(a=>a.memberId===ownId&&a.date===date);const count=state.availability.filter(a=>a.date===date&&a.available).length;return <Pressable key={date} accessibilityRole="button" accessibilityLabel={`${date}, ${own?.available===true?'available':own?.available===false?'unavailable':'no response'}, ${count} people available`} disabled={outside||busy||!ownId||!!state.event.archived} onPress={()=>{void run(()=>onToggle(date));}} style={[s.day,s.dayButton,outside&&s.outside,own?.available===true&&s.available,own?.available===false&&s.unavailable]}><Text style={s.dayNumber}>{Number(date.slice(-2))}</Text><Text style={s.dayCount}>{outside?'':`${count}/${state.members.length}`}</Text></Pressable>;})}</View></>}
  {!demo&&<Button label="Share invitation" secondary disabled={busy||!!state.event.archived} onPress={()=>{void run(async()=>{await Share.share({message:invitation(state)});});}}/>}</>;
}
function MemberEditor({member,busy,run,save}:{member?:Member;busy:boolean;run:(fn:()=>Promise<void>)=>Promise<void>;save:(value:unknown)=>Promise<void>}) {
  const [name,setName]=useState(member?.name||''),[email,setEmail]=useState(member?.email||'');
  return <View style={s.card}><Text style={s.heading}>{member?'Invitee details':'Add a person'}</Text><Field label="Name" value={name} onChange={setName} maxLength={80}/><Field label="Email" value={email} onChange={setEmail} keyboardType="email-address" maxLength={254}/><Button label={member?'Save person':'Add person'} disabled={busy} onPress={()=>{void run(async()=>{await save({action:'member',id:member?.id,name:name.trim(),email:email.trim().toLowerCase(),active:member?!!member.active:true});if(!member){setName('');setEmail('');}});}}/>{member&&<Button label={member.active?'Remove from plan':'Restore person'} secondary disabled={busy} onPress={()=>{void run(()=>save({action:'member',id:member.id,name:member.name,email:member.email||'',active:!member.active}));}}/>}</View>;
}
function Account({demo,email,busy,signOut,run,onDeleted}:{demo:boolean;email:string;busy:boolean;signOut:()=>void;run:(fn:()=>Promise<void>)=>Promise<void>;onDeleted:()=>void}) {
  const [confirm,setConfirm]=useState('');
  return <><Text style={s.title}>Your account</Text><Text style={s.body}>{email}</Text><Button label={demo?'Exit demo':'Sign out'} secondary disabled={busy} onPress={signOut}/>{!demo&&<View style={s.card}><Text style={s.heading}>Delete my account</Text><Text style={s.body}>This permanently deletes your account and all plans you own, including participants’ responses. It cannot be undone.</Text><Field label="Type DELETE to confirm" value={confirm} onChange={setConfirm} maxLength={6}/><Button label="Delete account and plans" disabled={busy||confirm!=='DELETE'} onPress={()=>Alert.alert('Delete your account?','Your plans and responses will be permanently deleted.',[{text:'Cancel',style:'cancel'},{text:'Delete account',style:'destructive',onPress:()=>{void run(async()=>{await api.request('/api/delete-account','POST',{confirm});await api.clearSession();onDeleted();});}}])}/></View>}</>;
}
const s=StyleSheet.create({
  safe:{flex:1,backgroundColor:'#FCF8F4'},header:{paddingHorizontal:20,paddingVertical:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderColor:'#E9E4DF'},logo:{width:130,height:60},content:{padding:22,gap:16,paddingBottom:30},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:1.5,color:teal},title:{fontSize:34,lineHeight:40,fontWeight:'700',color:ink},subtitle:{fontSize:19,lineHeight:27,color:muted},heading:{fontSize:20,fontWeight:'600',color:ink},body:{fontSize:15,lineHeight:23,color:ink},card:{backgroundColor:'white',borderRadius:22,padding:20,gap:16,borderWidth:1,borderColor:'#E9E4DF'},button:{backgroundColor:coral,borderRadius:14,minHeight:48,paddingHorizontal:16,paddingVertical:13,alignItems:'center',justifyContent:'center'},buttonText:{color:'white',fontWeight:'700',fontSize:15},secondary:{backgroundColor:'#E7F0EC'},secondaryText:{color:teal},disabled:{opacity:0.45},field:{gap:8},label:{color:ink,fontSize:14,fontWeight:'600'},input:{borderWidth:1,borderColor:'#D7DFDC',backgroundColor:'white',padding:14,borderRadius:12,fontSize:16,color:ink,minHeight:50},choices:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{padding:12,borderRadius:12,backgroundColor:'white',borderWidth:1,borderColor:'#D7DFDC'},chipSelected:{backgroundColor:teal,borderColor:teal},selectedText:{color:'white',fontSize:15},checkbox:{padding:14,borderRadius:12,backgroundColor:'#E7F0EC',minHeight:48},error:{color:'#9C342D',backgroundColor:'#FBE5E1',padding:14,borderRadius:12,fontSize:15},notice:{padding:14,borderRadius:14,backgroundColor:'#E7F0EC',gap:10},noticeText:{color:teal,fontSize:14,lineHeight:21,fontWeight:'600'},legal:{flexDirection:'row',gap:10,justifyContent:'center',paddingTop:20},copyright:{fontSize:11,color:muted,textAlign:'center'},loading:{padding:10},month:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},grid:{flexDirection:'row',flexWrap:'wrap'},day:{width:'14.285714%',height:64,padding:3,alignItems:'center',justifyContent:'center'},dayButton:{borderWidth:2,borderColor:'#FCF8F4',borderRadius:12,backgroundColor:'white'},dayLabel:{fontWeight:'600',color:muted},dayNumber:{fontSize:17,color:ink},dayCount:{fontSize:10,color:muted},outside:{opacity:0.25},available:{backgroundColor:'#BBDDD1'},unavailable:{backgroundColor:'#F4D1CB'}
});
