import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../worker/index.ts';
const env={SUPABASE_URL:'https://example.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public-test',SUPABASE_SECRET_KEY:'server-test',ADMIN_EMAIL:'office@hound-capital.com',ASSETS:{fetch:async()=>new Response('asset')}};
const post=(path,body,headers={})=>new Request('https://prod.test'+path,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
async function mock(handler,check){const old=globalThis.fetch;globalThis.fetch=handler;try{await check();}finally{globalThis.fetch=old;}}
test('native code verification returns a no-store session without affecting web cookies',async()=>{await mock(async(url,init)=>{assert.ok(url.endsWith('/auth/v1/verify'));assert.deepEqual(JSON.parse(init.body),{email:'person@example.com',token:'123456',type:'email'});return Response.json({access_token:'jwt',refresh_token:'r',expires_in:3600,user:{email_confirmed_at:'2026-10-01'}});},async()=>{const r=await worker.fetch(post('/api/mobile/session',{email:'PERSON@example.com',code:'123456'}),env);assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'no-store');assert.equal(r.headers.get('set-cookie'),null);assert.deepEqual(await r.json(),{accessToken:'jwt',refreshToken:'r',expiresIn:3600});});});
test('unconfirmed native identity cannot receive tokens',async()=>{await mock(async()=>Response.json({access_token:'jwt',refresh_token:'r',expires_in:3600,user:{}}),async()=>{assert.equal((await worker.fetch(post('/api/mobile/session',{email:'person@example.com',code:'123456'}),env)).status,403);});});
test('native refresh rotates tokens and rejects invalid input',async()=>{assert.equal((await worker.fetch(post('/api/mobile/refresh',{refreshToken:''}),env)).status,401);await mock(async(url,init)=>{assert.ok(url.endsWith('grant_type=refresh_token'));assert.deepEqual(JSON.parse(init.body),{refresh_token:'r'});return Response.json({access_token:'new',refresh_token:'rotated',expires_in:3600,user:{email_confirmed_at:'2026-10-01'}});},async()=>{const r=await worker.fetch(post('/api/mobile/refresh',{refreshToken:'r'}),env);assert.equal(r.status,200);assert.equal((await r.json()).refreshToken,'rotated');});});
test('bearer identity is verified before database access',async()=>{const calls=[];await mock(async(url,init)=>{calls.push(url);if(url.endsWith('/auth/v1/user')){assert.equal(init.headers.Authorization,'Bearer jwt');return Response.json({id:'verified-id',email_confirmed_at:'2026-10-01'});}const payload=JSON.parse(init.body);assert.equal(payload.p_user,'verified-id');assert.equal(payload.p_email,null);return Response.json({plans:[]});},async()=>{const r=await worker.fetch(new Request('https://prod.test/api/state?view=plans',{headers:{authorization:'Bearer jwt'}}),env);assert.equal(r.status,200);assert.equal(calls.length,2);});});
test('malformed or expired bearer never falls back to an existing cookie',async()=>{assert.equal((await worker.fetch(new Request('https://prod.test/api/profile',{headers:{authorization:'Basic nope',cookie:'prod_session=valid'}}),env)).status,401);await mock(async()=>Response.json({},{status:401}),async()=>{assert.equal((await worker.fetch(new Request('https://prod.test/api/profile',{headers:{authorization:'Bearer expired',cookie:'prod_session=valid'}}),env)).status,401);});});
test('cross-origin requests cannot exchange OTPs for native sessions',async()=>{assert.equal((await worker.fetch(post('/api/mobile/session',{email:'person@example.com',code:'123456'},{origin:'https://evil.test'}),env)).status,403);});
