import { useState } from 'react';

const operator = 'Hound Capital Ltd (company number 14932445), Mondays House, Farm Road, Bracklesham Bay, West Sussex, PO20 8JT';
export const TERMS_VERSION = '2026-09-27';

export function LegalPage(){return <main className="legal-page"><a href="/"><img src="/prod-logo.png" alt="prod." width="150"/></a><h1>terms.</h1><p>Effective 27 September 2026 · SMS privacy information updated 2 October 2026 · <a href="mailto:office@hound-capital.com">Contact us</a></p><nav aria-label="Legal documents"><a href="#terms">Terms of Service</a><a href="#privacy">Privacy Policy</a><a href="#cookies">Cookies</a><a href="/account">Account deletion</a></nav>
<section id="terms"><h2>Terms of Service</h2>
<p><strong>Operator.</strong> prod. is provided by {operator}, England and Wales. Contact office@hound-capital.com.</p>
<p><strong>Eligibility.</strong> You must be 18 or older to create an account or use prod. Do not register or respond if you are under 18. We may suspend accounts where we reasonably believe this condition is not met.</p>
<p><strong>The service.</strong> Organisers create plans and invite participants to indicate their availability. Only invite people where it is reasonable to do so. Do not add sensitive details to plan names; impersonate others; scrape the service; or access plans without authority.</p>
<p><strong>Accounts and plans.</strong> Keep your sign-in email and mobile number secure. SMS responses require a verification code sent to the invited number. An invited email and plan link currently allow access to that participant’s record, so do not share links widely. We may suspend abusive use. Organisers may archive plans or delete their account. Account deletion removes their plans and participants’ responses from live systems, subject to the retention and backup information below. Participants may ask us to remove their details.</p>
<p><strong>Changes and availability.</strong> We aim to provide a reliable service but cannot promise uninterrupted access or a suitable date. We may change the service and these Terms, giving notice of material changes where reasonably possible. Where fresh agreement is needed, we will ask for it.</p>
<p><strong>Personal data.</strong> The Privacy Policy explains our use of personal information. These Terms do not authorise sale of identifiable personal data. We may use genuinely anonymous aggregate statistics where people cannot reasonably be identified. Any new identifiable-data sharing purpose requires its own assessment and notice.</p>
<p><strong>Liability and law.</strong> Nothing limits liability for fraud, death or personal injury caused by negligence, or rights that cannot lawfully be limited. We are responsible for foreseeable loss caused by our breach or failure to use reasonable care and skill. English law applies, subject to mandatory consumer protections.</p></section>
<section id="privacy"><h2>Privacy Policy</h2>
<p><strong>Controller.</strong> {operator} controls personal information used for prod. Contact office@hound-capital.com to exercise your rights. You can complain to the Information Commissioner’s Office at <a href="https://ico.org.uk/">ico.org.uk</a>.</p>
<p><strong>Information.</strong> Organisers provide a name, email, sex selection, age range and Terms acceptance. We hold plan names, dates, invitee names, optional emails and mobile numbers, SMS preferences, permission records, delivery records, availability, authentication details, technical security data and support messages. Organisers provide invitee names and contact details; participants provide their own availability. Avoid sensitive information in free-text fields.</p>
<table><thead><tr><th>Use</th><th>Lawful basis</th></tr></thead><tbody><tr><td>Accounts, plans and responses</td><td>Contract with organisers</td></tr><tr><td>Invitations and group coordination</td><td>Legitimate interests of organisers and participants, balanced against participants’ rights</td></tr><tr><td>Security, abuse prevention and support</td><td>Legitimate interests or legal obligation, as applicable</td></tr><tr><td>Terms acceptance records</td><td>Legitimate interests in documenting the agreement</td></tr></tbody></table>
<p><strong>Sharing.</strong> Cloudflare and Supabase, and their authorised providers, host, authenticate and process service data. Twilio delivers verification codes, event invitations and reminders, processing recipient numbers, message contents and delivery details. Organisers can see invitee emails, mobile numbers, SMS permission and invitation status; people on a plan can see names and availability. We may disclose information when legally required. We do not currently send marketing emails or sell identifiable personal information.</p>
<p><strong>Event texts.</strong> We send verification codes when you request phone sign-in. Event invitations and one reminder after 24 hours without an availability response require your recorded SMS permission. You can turn event texts off in the phone calendar or reply STOP. These texts are for event coordination, not marketing. We keep permission and suppression records to respect your choices; contact us to request their removal. Only selected invitees’ contact details are stored, not your whole address book.</p>
<p><strong>Retention.</strong> Account and plan information is kept while needed to provide the service. Deleting an organiser account removes its plans, participants and responses from live records. Security logs and backups may be retained for limited operational periods under provider schedules. Contact us for information about a specific record or to request erasure. International processing and transfer safeguards depend on our providers and their configured services; contact us for details.</p>
<p><strong>Your rights.</strong> Depending on the circumstances, you may request access, correction, deletion, restriction or portability, or object to legitimate-interest processing. We verify requests proportionately and respond within the applicable legal period. We do not make solely automated decisions with legal or similarly significant effects. prod. is intended for adults; we collect an age category rather than a date of birth.</p></section>
<section id="cookies"><h2>Cookies and device storage</h2><p>We use a first-party, HTTP-only <code>prod_session</code> cookie to keep organisers signed in for up to one hour. An invitee who confirms they are 18 or over receives a first-party <code>prod_adult</code> cookie for up to one hour to remember that choice during a visit. Phone respondents receive a first-party, HTTP-only <code>prod_phone_session</code> cookie for up to one hour after verification. These are necessary to provide the requested account and invitation functions. We have not added advertising or optional analytics cookies. Hosting providers may use essential security technologies. If optional tracking is introduced, we will explain it and seek consent where required before use.</p></section>
<p><a href="/">Return to prod.</a></p></main>}

export function AccountPage(){const [status,setStatus]=useState('');const [confirm,setConfirm]=useState('');async function remove(){setStatus('Deleting…');try{const r=await fetch('/api/delete-account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({confirm})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not delete your account.');window.location.assign('/');}catch(e){setStatus(e instanceof Error?e.message:'Could not delete your account.')}}return <main className="legal-page"><a href="/"><img src="/prod-logo.png" alt="prod." width="150"/></a><h1>Delete my account</h1><p>This permanently deletes your account and every plan you own, including participants’ responses. It cannot be undone through prod. If you only want a participant entry removed, contact <a href="mailto:office@hound-capital.com">office@hound-capital.com</a>.</p><label>Type DELETE to confirm<input value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="off"/></label><button className="primary" disabled={confirm!=='DELETE'||status==='Deleting…'} onClick={()=>void remove()}>Delete my account and plans</button>{status&&<p role="status">{status}</p>}<p><a href="/terms">Terms and Privacy Policy</a></p></main>}
